---
- include_role:
    name: openio-service
  vars:
    openio_service_type: "oio-netdata"
    openio_service_namespace: "{{ openio_netdata_namespace }}"
    openio_service_maintenance_mode: "{{ openio_netdata_maintenance_mode }}"
    openio_service_packages:
      - oio-netdata
    openio_service_directories:
      - path: "{{ openio_service_volume }}"
    openio_service_configuration_files:
      - name: netdata.conf
      - name: apps_groups.conf
      - name: stream.conf
    openio_service_services:
      - command: "/usr/sbin/oio-netdata -c {{ openio_service_conf_dir }}/netdata.conf -D"
        uid: root
        gid: root
    openio_service_checks:
      - uri:
          url: "http://{{ openio_netdata_bind_address }}:{{ openio_netdata_bind_port }}/api/v1/info"
        retries: 10
        delay: 2
...
